export const types = {
    AGREGAR_PRODUCTO: '@AGREGAR_PRODUCTO',
    AGREGAR_PRODUCTO_EXITO: '@AGREGAR_PRODUCTO_EXITO',
    AGREGAR_PRODUCTO_ERROR: '@AGREGAR_PRODUCTO_ERROR',

    COMENZAR_DESCARGA_PRODUCTOS: '@COMENZAR_DESCARGA_PRODUCTOS',
    DESCARGA_PRODUCTOS_EXITO: '@DESCARGA_PRODUCTOS_EXITO',
    DESCARGA_PRODUCTOS_ERROR: '@DESCARGA_PRODUCTOS_ERROR',

    OBTENER_PRODUCTO_ELIMINAR: '@OBTENER_PRODUCTO_ELIMINAR',
    PRODUCTO_ELIMINADO_EXITO: '@PRODUCTO_ELIMINADO_EXITO',
    PRODUCTO_ELIMINADO_ERROR: '@PRODUCTO_ELIMINADO_ERROR',
    
    OBTENER_PRODUCTO_EDITAR: '@OBTENER_PRODUCTO_EDITAR',
    COMENZAR_EDICION_PRODUCTO: '@COMENZAR_EDICION_PRODUCTO',
    PRODUCTO_EDITAR_EXITO: '@PRODUCTO_EDITAR_EXITO',
    PRODUCTO_EDITAR_ERROR: '@PRODUCTO_EDITAR_ERROR',
}